name: Java CI with Maven and SonarCloud Scan and Quality Gate

on:
  push:
    branches: [ "main","development"]
  pull_request:
    branches: [ "main","development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build, Test and SonarCloud Analysis
      run: mvn -B clean verify sonar:sonar \
        -Dsonar.projectKey=IDM-MICROSERVICES_auth-service \
        -Dsonar.organization=idm-microservices \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: SonarCloud Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@v1
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
